// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT89dlRsoAd3gptnwb3lq3CBf62z4jOQM',
    appId: '1:709244109082:web:78502e970635c46e042ca3',
    messagingSenderId: '709244109082',
    projectId: 'buildbyte-a552f',
    authDomain: 'buildbyte-a552f.firebaseapp.com',
    storageBucket: 'buildbyte-a552f.firebasestorage.app',
    measurementId: 'G-VTP5GT0WYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQsFOwsNYXSQXZJYWEMAgXmiFwht0x_T0',
    appId: '1:709244109082:android:b10c19e3c6b0bfd6042ca3',
    messagingSenderId: '709244109082',
    projectId: 'buildbyte-a552f',
    storageBucket: 'buildbyte-a552f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOQDjrjW2SXNz2fjTNbvO5zA1f6E_Vg1s',
    appId: '1:709244109082:ios:050c0d51932c4d00042ca3',
    messagingSenderId: '709244109082',
    projectId: 'buildbyte-a552f',
    storageBucket: 'buildbyte-a552f.firebasestorage.app',
    iosBundleId: 'com.example.buildByte',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOQDjrjW2SXNz2fjTNbvO5zA1f6E_Vg1s',
    appId: '1:709244109082:ios:050c0d51932c4d00042ca3',
    messagingSenderId: '709244109082',
    projectId: 'buildbyte-a552f',
    storageBucket: 'buildbyte-a552f.firebasestorage.app',
    iosBundleId: 'com.example.buildByte',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDT89dlRsoAd3gptnwb3lq3CBf62z4jOQM',
    appId: '1:709244109082:web:a5b71cc526fe262f042ca3',
    messagingSenderId: '709244109082',
    projectId: 'buildbyte-a552f',
    authDomain: 'buildbyte-a552f.firebaseapp.com',
    storageBucket: 'buildbyte-a552f.firebasestorage.app',
    measurementId: 'G-H9DJSGJRPX',
  );
}
